image: softsec/isos:latest

# Define the stages
stages:
  - build
  - analyze



build:
  stage: build
  script:
      - scripts/build.sh
  artifacts:
    name: "build_artifacts_$CI_COMMIT_SHORT_SHA"
    paths:
      - artifacts/

analyze:
  stage: analyze
  script:
      - scripts/analyze.sh
  artifacts:
    name: "analyze_artifacts_$CI_COMMIT_SHORT_SHA"
    paths:
      - artifacts/
